services: 
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.psql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  python:
    build: .
    depends_on:
      - db
    volumes:
      - .:/app
    working_dir: /app
    environment:
      DATABASE_URL: ${DATABASE_URL}

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"

volumes:
  postgres_data:
    driver: local

